// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: routeiq/v1/admin/billing.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Routeiq.V1.Admin {

  /// <summary>Holder for reflection information generated from routeiq/v1/admin/billing.proto</summary>
  public static partial class BillingReflection {

    #region Descriptor
    /// <summary>File descriptor for routeiq/v1/admin/billing.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BillingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5yb3V0ZWlxL3YxL2FkbWluL2JpbGxpbmcucHJvdG8SEHJvdXRlaXEudjEu",
            "YWRtaW4aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8aI3JvdXRl",
            "aXEvdjEvYWRtaW4vb3JnYW5pemF0aW9uLnByb3RvIt8CCgxVc2FnZVN1bW1h",
            "cnkSJwoPb3JnYW5pemF0aW9uX2lkGAEgASgJUg5vcmdhbml6YXRpb25JZBI9",
            "CgxwZXJpb2Rfc3RhcnQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0",
            "YW1wUgtwZXJpb2RTdGFydBI5CgpwZXJpb2RfZW5kGAMgASgLMhouZ29vZ2xl",
            "LnByb3RvYnVmLlRpbWVzdGFtcFIJcGVyaW9kRW5kEicKD2V2ZW50c19pbmdl",
            "c3RlZBgEIAEoA1IOZXZlbnRzSW5nZXN0ZWQSKwoRbWV0cmljc19ldmFsdWF0",
            "ZWQYBSABKANSEG1ldHJpY3NFdmFsdWF0ZWQSMAoUZnJvbnRpZXJfanVkZ2Vf",
            "Y2FsbHMYBiABKANSEmZyb250aWVySnVkZ2VDYWxscxIkCg50b3RhbF9jb3N0",
            "X3VzZBgHIAEoAVIMdG90YWxDb3N0VXNkIuYBCgVRdW90YRInCg9vcmdhbml6",
            "YXRpb25faWQYASABKAlSDm9yZ2FuaXphdGlvbklkEioKBHRpZXIYAiABKA4y",
            "Fi5yb3V0ZWlxLnYxLmFkbWluLlRpZXJSBHRpZXISKAoQZXZlbnRzX3Blcl9t",
            "b250aBgDIAEoA1IOZXZlbnRzUGVyTW9udGgSNwoYZnJvbnRpZXJfY2FsbHNf",
            "cGVyX21vbnRoGAQgASgDUhVmcm9udGllckNhbGxzUGVyTW9udGgSJQoOcmV0",
            "ZW50aW9uX2RheXMYBSABKANSDXJldGVudGlvbkRheXMitAEKD0dldFVzYWdl",
            "UmVxdWVzdBInCg9vcmdhbml6YXRpb25faWQYASABKAlSDm9yZ2FuaXphdGlv",
            "bklkEj0KDHBlcmlvZF9zdGFydBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5U",
            "aW1lc3RhbXBSC3BlcmlvZFN0YXJ0EjkKCnBlcmlvZF9lbmQYAyABKAsyGi5n",
            "b29nbGUucHJvdG9idWYuVGltZXN0YW1wUglwZXJpb2RFbmQiOgoPR2V0UXVv",
            "dGFSZXF1ZXN0EicKD29yZ2FuaXphdGlvbl9pZBgBIAEoCVIOb3JnYW5pemF0",
            "aW9uSWQypwEKDkJpbGxpbmdTZXJ2aWNlEk0KCEdldFVzYWdlEiEucm91dGVp",
            "cS52MS5hZG1pbi5HZXRVc2FnZVJlcXVlc3QaHi5yb3V0ZWlxLnYxLmFkbWlu",
            "LlVzYWdlU3VtbWFyeRJGCghHZXRRdW90YRIhLnJvdXRlaXEudjEuYWRtaW4u",
            "R2V0UXVvdGFSZXF1ZXN0Ghcucm91dGVpcS52MS5hZG1pbi5RdW90YUKMAQou",
            "YnVpbGQuYnVmLmdlbi5zc2ZvcmdlLnJvdXRlaXEucm91dGVpcS52MS5hZG1p",
            "bkIMQmlsbGluZ1Byb3RvWkxidWYuYnVpbGQvZ2VuL2dvL3NzZm9yZ2Uvcm91",
            "dGVpcS9wcm90b2NvbGJ1ZmZlcnMvZ28vcm91dGVpcS92MS9hZG1pbjthZG1p",
            "bnYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Routeiq.V1.Admin.OrganizationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Admin.UsageSummary), global::Routeiq.V1.Admin.UsageSummary.Parser, new[]{ "OrganizationId", "PeriodStart", "PeriodEnd", "EventsIngested", "MetricsEvaluated", "FrontierJudgeCalls", "TotalCostUsd" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Admin.Quota), global::Routeiq.V1.Admin.Quota.Parser, new[]{ "OrganizationId", "Tier", "EventsPerMonth", "FrontierCallsPerMonth", "RetentionDays" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Admin.GetUsageRequest), global::Routeiq.V1.Admin.GetUsageRequest.Parser, new[]{ "OrganizationId", "PeriodStart", "PeriodEnd" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Admin.GetQuotaRequest), global::Routeiq.V1.Admin.GetQuotaRequest.Parser, new[]{ "OrganizationId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UsageSummary : pb::IMessage<UsageSummary>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UsageSummary> _parser = new pb::MessageParser<UsageSummary>(() => new UsageSummary());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UsageSummary> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Admin.BillingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsageSummary() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsageSummary(UsageSummary other) : this() {
      organizationId_ = other.organizationId_;
      periodStart_ = other.periodStart_ != null ? other.periodStart_.Clone() : null;
      periodEnd_ = other.periodEnd_ != null ? other.periodEnd_.Clone() : null;
      eventsIngested_ = other.eventsIngested_;
      metricsEvaluated_ = other.metricsEvaluated_;
      frontierJudgeCalls_ = other.frontierJudgeCalls_;
      totalCostUsd_ = other.totalCostUsd_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsageSummary Clone() {
      return new UsageSummary(this);
    }

    /// <summary>Field number for the "organization_id" field.</summary>
    public const int OrganizationIdFieldNumber = 1;
    private string organizationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "period_start" field.</summary>
    public const int PeriodStartFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp periodStart_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp PeriodStart {
      get { return periodStart_; }
      set {
        periodStart_ = value;
      }
    }

    /// <summary>Field number for the "period_end" field.</summary>
    public const int PeriodEndFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp periodEnd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp PeriodEnd {
      get { return periodEnd_; }
      set {
        periodEnd_ = value;
      }
    }

    /// <summary>Field number for the "events_ingested" field.</summary>
    public const int EventsIngestedFieldNumber = 4;
    private long eventsIngested_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EventsIngested {
      get { return eventsIngested_; }
      set {
        eventsIngested_ = value;
      }
    }

    /// <summary>Field number for the "metrics_evaluated" field.</summary>
    public const int MetricsEvaluatedFieldNumber = 5;
    private long metricsEvaluated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MetricsEvaluated {
      get { return metricsEvaluated_; }
      set {
        metricsEvaluated_ = value;
      }
    }

    /// <summary>Field number for the "frontier_judge_calls" field.</summary>
    public const int FrontierJudgeCallsFieldNumber = 6;
    private long frontierJudgeCalls_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FrontierJudgeCalls {
      get { return frontierJudgeCalls_; }
      set {
        frontierJudgeCalls_ = value;
      }
    }

    /// <summary>Field number for the "total_cost_usd" field.</summary>
    public const int TotalCostUsdFieldNumber = 7;
    private double totalCostUsd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TotalCostUsd {
      get { return totalCostUsd_; }
      set {
        totalCostUsd_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UsageSummary);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UsageSummary other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrganizationId != other.OrganizationId) return false;
      if (!object.Equals(PeriodStart, other.PeriodStart)) return false;
      if (!object.Equals(PeriodEnd, other.PeriodEnd)) return false;
      if (EventsIngested != other.EventsIngested) return false;
      if (MetricsEvaluated != other.MetricsEvaluated) return false;
      if (FrontierJudgeCalls != other.FrontierJudgeCalls) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TotalCostUsd, other.TotalCostUsd)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (periodStart_ != null) hash ^= PeriodStart.GetHashCode();
      if (periodEnd_ != null) hash ^= PeriodEnd.GetHashCode();
      if (EventsIngested != 0L) hash ^= EventsIngested.GetHashCode();
      if (MetricsEvaluated != 0L) hash ^= MetricsEvaluated.GetHashCode();
      if (FrontierJudgeCalls != 0L) hash ^= FrontierJudgeCalls.GetHashCode();
      if (TotalCostUsd != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TotalCostUsd);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (periodStart_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PeriodStart);
      }
      if (periodEnd_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PeriodEnd);
      }
      if (EventsIngested != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(EventsIngested);
      }
      if (MetricsEvaluated != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(MetricsEvaluated);
      }
      if (FrontierJudgeCalls != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(FrontierJudgeCalls);
      }
      if (TotalCostUsd != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(TotalCostUsd);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (periodStart_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PeriodStart);
      }
      if (periodEnd_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PeriodEnd);
      }
      if (EventsIngested != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(EventsIngested);
      }
      if (MetricsEvaluated != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(MetricsEvaluated);
      }
      if (FrontierJudgeCalls != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(FrontierJudgeCalls);
      }
      if (TotalCostUsd != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(TotalCostUsd);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationId);
      }
      if (periodStart_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PeriodStart);
      }
      if (periodEnd_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PeriodEnd);
      }
      if (EventsIngested != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EventsIngested);
      }
      if (MetricsEvaluated != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MetricsEvaluated);
      }
      if (FrontierJudgeCalls != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FrontierJudgeCalls);
      }
      if (TotalCostUsd != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UsageSummary other) {
      if (other == null) {
        return;
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.periodStart_ != null) {
        if (periodStart_ == null) {
          PeriodStart = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        PeriodStart.MergeFrom(other.PeriodStart);
      }
      if (other.periodEnd_ != null) {
        if (periodEnd_ == null) {
          PeriodEnd = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        PeriodEnd.MergeFrom(other.PeriodEnd);
      }
      if (other.EventsIngested != 0L) {
        EventsIngested = other.EventsIngested;
      }
      if (other.MetricsEvaluated != 0L) {
        MetricsEvaluated = other.MetricsEvaluated;
      }
      if (other.FrontierJudgeCalls != 0L) {
        FrontierJudgeCalls = other.FrontierJudgeCalls;
      }
      if (other.TotalCostUsd != 0D) {
        TotalCostUsd = other.TotalCostUsd;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
          case 18: {
            if (periodStart_ == null) {
              PeriodStart = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PeriodStart);
            break;
          }
          case 26: {
            if (periodEnd_ == null) {
              PeriodEnd = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PeriodEnd);
            break;
          }
          case 32: {
            EventsIngested = input.ReadInt64();
            break;
          }
          case 40: {
            MetricsEvaluated = input.ReadInt64();
            break;
          }
          case 48: {
            FrontierJudgeCalls = input.ReadInt64();
            break;
          }
          case 57: {
            TotalCostUsd = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
          case 18: {
            if (periodStart_ == null) {
              PeriodStart = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PeriodStart);
            break;
          }
          case 26: {
            if (periodEnd_ == null) {
              PeriodEnd = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PeriodEnd);
            break;
          }
          case 32: {
            EventsIngested = input.ReadInt64();
            break;
          }
          case 40: {
            MetricsEvaluated = input.ReadInt64();
            break;
          }
          case 48: {
            FrontierJudgeCalls = input.ReadInt64();
            break;
          }
          case 57: {
            TotalCostUsd = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Quota : pb::IMessage<Quota>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Quota> _parser = new pb::MessageParser<Quota>(() => new Quota());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Quota> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Admin.BillingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Quota() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Quota(Quota other) : this() {
      organizationId_ = other.organizationId_;
      tier_ = other.tier_;
      eventsPerMonth_ = other.eventsPerMonth_;
      frontierCallsPerMonth_ = other.frontierCallsPerMonth_;
      retentionDays_ = other.retentionDays_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Quota Clone() {
      return new Quota(this);
    }

    /// <summary>Field number for the "organization_id" field.</summary>
    public const int OrganizationIdFieldNumber = 1;
    private string organizationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tier" field.</summary>
    public const int TierFieldNumber = 2;
    private global::Routeiq.V1.Admin.Tier tier_ = global::Routeiq.V1.Admin.Tier.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Routeiq.V1.Admin.Tier Tier {
      get { return tier_; }
      set {
        tier_ = value;
      }
    }

    /// <summary>Field number for the "events_per_month" field.</summary>
    public const int EventsPerMonthFieldNumber = 3;
    private long eventsPerMonth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EventsPerMonth {
      get { return eventsPerMonth_; }
      set {
        eventsPerMonth_ = value;
      }
    }

    /// <summary>Field number for the "frontier_calls_per_month" field.</summary>
    public const int FrontierCallsPerMonthFieldNumber = 4;
    private long frontierCallsPerMonth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FrontierCallsPerMonth {
      get { return frontierCallsPerMonth_; }
      set {
        frontierCallsPerMonth_ = value;
      }
    }

    /// <summary>Field number for the "retention_days" field.</summary>
    public const int RetentionDaysFieldNumber = 5;
    private long retentionDays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RetentionDays {
      get { return retentionDays_; }
      set {
        retentionDays_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Quota);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Quota other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrganizationId != other.OrganizationId) return false;
      if (Tier != other.Tier) return false;
      if (EventsPerMonth != other.EventsPerMonth) return false;
      if (FrontierCallsPerMonth != other.FrontierCallsPerMonth) return false;
      if (RetentionDays != other.RetentionDays) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (Tier != global::Routeiq.V1.Admin.Tier.Unspecified) hash ^= Tier.GetHashCode();
      if (EventsPerMonth != 0L) hash ^= EventsPerMonth.GetHashCode();
      if (FrontierCallsPerMonth != 0L) hash ^= FrontierCallsPerMonth.GetHashCode();
      if (RetentionDays != 0L) hash ^= RetentionDays.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (Tier != global::Routeiq.V1.Admin.Tier.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Tier);
      }
      if (EventsPerMonth != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(EventsPerMonth);
      }
      if (FrontierCallsPerMonth != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(FrontierCallsPerMonth);
      }
      if (RetentionDays != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(RetentionDays);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (Tier != global::Routeiq.V1.Admin.Tier.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Tier);
      }
      if (EventsPerMonth != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(EventsPerMonth);
      }
      if (FrontierCallsPerMonth != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(FrontierCallsPerMonth);
      }
      if (RetentionDays != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(RetentionDays);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationId);
      }
      if (Tier != global::Routeiq.V1.Admin.Tier.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Tier);
      }
      if (EventsPerMonth != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EventsPerMonth);
      }
      if (FrontierCallsPerMonth != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FrontierCallsPerMonth);
      }
      if (RetentionDays != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RetentionDays);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Quota other) {
      if (other == null) {
        return;
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.Tier != global::Routeiq.V1.Admin.Tier.Unspecified) {
        Tier = other.Tier;
      }
      if (other.EventsPerMonth != 0L) {
        EventsPerMonth = other.EventsPerMonth;
      }
      if (other.FrontierCallsPerMonth != 0L) {
        FrontierCallsPerMonth = other.FrontierCallsPerMonth;
      }
      if (other.RetentionDays != 0L) {
        RetentionDays = other.RetentionDays;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
          case 16: {
            Tier = (global::Routeiq.V1.Admin.Tier) input.ReadEnum();
            break;
          }
          case 24: {
            EventsPerMonth = input.ReadInt64();
            break;
          }
          case 32: {
            FrontierCallsPerMonth = input.ReadInt64();
            break;
          }
          case 40: {
            RetentionDays = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
          case 16: {
            Tier = (global::Routeiq.V1.Admin.Tier) input.ReadEnum();
            break;
          }
          case 24: {
            EventsPerMonth = input.ReadInt64();
            break;
          }
          case 32: {
            FrontierCallsPerMonth = input.ReadInt64();
            break;
          }
          case 40: {
            RetentionDays = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetUsageRequest : pb::IMessage<GetUsageRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetUsageRequest> _parser = new pb::MessageParser<GetUsageRequest>(() => new GetUsageRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetUsageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Admin.BillingReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetUsageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetUsageRequest(GetUsageRequest other) : this() {
      organizationId_ = other.organizationId_;
      periodStart_ = other.periodStart_ != null ? other.periodStart_.Clone() : null;
      periodEnd_ = other.periodEnd_ != null ? other.periodEnd_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetUsageRequest Clone() {
      return new GetUsageRequest(this);
    }

    /// <summary>Field number for the "organization_id" field.</summary>
    public const int OrganizationIdFieldNumber = 1;
    private string organizationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "period_start" field.</summary>
    public const int PeriodStartFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp periodStart_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp PeriodStart {
      get { return periodStart_; }
      set {
        periodStart_ = value;
      }
    }

    /// <summary>Field number for the "period_end" field.</summary>
    public const int PeriodEndFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp periodEnd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp PeriodEnd {
      get { return periodEnd_; }
      set {
        periodEnd_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetUsageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetUsageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrganizationId != other.OrganizationId) return false;
      if (!object.Equals(PeriodStart, other.PeriodStart)) return false;
      if (!object.Equals(PeriodEnd, other.PeriodEnd)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (periodStart_ != null) hash ^= PeriodStart.GetHashCode();
      if (periodEnd_ != null) hash ^= PeriodEnd.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (periodStart_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PeriodStart);
      }
      if (periodEnd_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PeriodEnd);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (periodStart_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PeriodStart);
      }
      if (periodEnd_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PeriodEnd);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationId);
      }
      if (periodStart_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PeriodStart);
      }
      if (periodEnd_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PeriodEnd);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetUsageRequest other) {
      if (other == null) {
        return;
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.periodStart_ != null) {
        if (periodStart_ == null) {
          PeriodStart = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        PeriodStart.MergeFrom(other.PeriodStart);
      }
      if (other.periodEnd_ != null) {
        if (periodEnd_ == null) {
          PeriodEnd = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        PeriodEnd.MergeFrom(other.PeriodEnd);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
          case 18: {
            if (periodStart_ == null) {
              PeriodStart = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PeriodStart);
            break;
          }
          case 26: {
            if (periodEnd_ == null) {
              PeriodEnd = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PeriodEnd);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
          case 18: {
            if (periodStart_ == null) {
              PeriodStart = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PeriodStart);
            break;
          }
          case 26: {
            if (periodEnd_ == null) {
              PeriodEnd = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PeriodEnd);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetQuotaRequest : pb::IMessage<GetQuotaRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetQuotaRequest> _parser = new pb::MessageParser<GetQuotaRequest>(() => new GetQuotaRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetQuotaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Admin.BillingReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetQuotaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetQuotaRequest(GetQuotaRequest other) : this() {
      organizationId_ = other.organizationId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetQuotaRequest Clone() {
      return new GetQuotaRequest(this);
    }

    /// <summary>Field number for the "organization_id" field.</summary>
    public const int OrganizationIdFieldNumber = 1;
    private string organizationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetQuotaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetQuotaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrganizationId != other.OrganizationId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetQuotaRequest other) {
      if (other == null) {
        return;
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
