// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: routeiq/v1/telemetry/conventions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Routeiq.V1.Telemetry {

  /// <summary>Holder for reflection information generated from routeiq/v1/telemetry/conventions.proto</summary>
  public static partial class ConventionsReflection {

    #region Descriptor
    /// <summary>File descriptor for routeiq/v1/telemetry/conventions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConventionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZyb3V0ZWlxL3YxL3RlbGVtZXRyeS9jb252ZW50aW9ucy5wcm90bxIUcm91",
            "dGVpcS52MS50ZWxlbWV0cnkaI3JvdXRlaXEvdjEvdGVsZW1ldHJ5L2VudGl0",
            "aWVzLnByb3RvIsEBChJTZW1hbnRpY0NvbnZlbnRpb24SKAoQcHJvdG9fZmll",
            "bGRfcGF0aBgBIAEoCVIOcHJvdG9GaWVsZFBhdGgSLAoSb3RlbF9hdHRyaWJ1",
            "dGVfa2V5GAIgASgJUhBvdGVsQXR0cmlidXRlS2V5EjcKBHR5cGUYAyABKA4y",
            "Iy5yb3V0ZWlxLnYxLnRlbGVtZXRyeS5BdHRyaWJ1dGVUeXBlUgR0eXBlEhoK",
            "CHJlcXVpcmVkGAQgASgIUghyZXF1aXJlZCJgChJDb252ZW50aW9uUmVnaXN0",
            "cnkSSgoLY29udmVudGlvbnMYASADKAsyKC5yb3V0ZWlxLnYxLnRlbGVtZXRy",
            "eS5TZW1hbnRpY0NvbnZlbnRpb25SC2NvbnZlbnRpb25zQpwBCjJidWlsZC5i",
            "dWYuZ2VuLnNzZm9yZ2Uucm91dGVpcS5yb3V0ZWlxLnYxLnRlbGVtZXRyeUIQ",
            "Q29udmVudGlvbnNQcm90b1pUYnVmLmJ1aWxkL2dlbi9nby9zc2ZvcmdlL3Jv",
            "dXRlaXEvcHJvdG9jb2xidWZmZXJzL2dvL3JvdXRlaXEvdjEvdGVsZW1ldHJ5",
            "O3RlbGVtZXRyeXYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Routeiq.V1.Telemetry.EntitiesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Telemetry.SemanticConvention), global::Routeiq.V1.Telemetry.SemanticConvention.Parser, new[]{ "ProtoFieldPath", "OtelAttributeKey", "Type", "Required" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Telemetry.ConventionRegistry), global::Routeiq.V1.Telemetry.ConventionRegistry.Parser, new[]{ "Conventions" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// SemanticConvention maps a typed proto field to its OTel span attribute key.
  /// Read by the SDK code generator to emit the right attribute keys.
  /// Read by routeiq_validator (collector component) to validate incoming spans.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SemanticConvention : pb::IMessage<SemanticConvention>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SemanticConvention> _parser = new pb::MessageParser<SemanticConvention>(() => new SemanticConvention());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SemanticConvention> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Telemetry.ConventionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SemanticConvention() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SemanticConvention(SemanticConvention other) : this() {
      protoFieldPath_ = other.protoFieldPath_;
      otelAttributeKey_ = other.otelAttributeKey_;
      type_ = other.type_;
      required_ = other.required_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SemanticConvention Clone() {
      return new SemanticConvention(this);
    }

    /// <summary>Field number for the "proto_field_path" field.</summary>
    public const int ProtoFieldPathFieldNumber = 1;
    private string protoFieldPath_ = "";
    /// <summary>
    /// e.g. "TaskEvent.completion_status"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProtoFieldPath {
      get { return protoFieldPath_; }
      set {
        protoFieldPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "otel_attribute_key" field.</summary>
    public const int OtelAttributeKeyFieldNumber = 2;
    private string otelAttributeKey_ = "";
    /// <summary>
    /// e.g. "routeiq.task.completion_status"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OtelAttributeKey {
      get { return otelAttributeKey_; }
      set {
        otelAttributeKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private global::Routeiq.V1.Telemetry.AttributeType type_ = global::Routeiq.V1.Telemetry.AttributeType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Routeiq.V1.Telemetry.AttributeType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "required" field.</summary>
    public const int RequiredFieldNumber = 4;
    private bool required_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Required {
      get { return required_; }
      set {
        required_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SemanticConvention);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SemanticConvention other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProtoFieldPath != other.ProtoFieldPath) return false;
      if (OtelAttributeKey != other.OtelAttributeKey) return false;
      if (Type != other.Type) return false;
      if (Required != other.Required) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProtoFieldPath.Length != 0) hash ^= ProtoFieldPath.GetHashCode();
      if (OtelAttributeKey.Length != 0) hash ^= OtelAttributeKey.GetHashCode();
      if (Type != global::Routeiq.V1.Telemetry.AttributeType.Unspecified) hash ^= Type.GetHashCode();
      if (Required != false) hash ^= Required.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProtoFieldPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ProtoFieldPath);
      }
      if (OtelAttributeKey.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OtelAttributeKey);
      }
      if (Type != global::Routeiq.V1.Telemetry.AttributeType.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      if (Required != false) {
        output.WriteRawTag(32);
        output.WriteBool(Required);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProtoFieldPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ProtoFieldPath);
      }
      if (OtelAttributeKey.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OtelAttributeKey);
      }
      if (Type != global::Routeiq.V1.Telemetry.AttributeType.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      if (Required != false) {
        output.WriteRawTag(32);
        output.WriteBool(Required);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProtoFieldPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProtoFieldPath);
      }
      if (OtelAttributeKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OtelAttributeKey);
      }
      if (Type != global::Routeiq.V1.Telemetry.AttributeType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Required != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SemanticConvention other) {
      if (other == null) {
        return;
      }
      if (other.ProtoFieldPath.Length != 0) {
        ProtoFieldPath = other.ProtoFieldPath;
      }
      if (other.OtelAttributeKey.Length != 0) {
        OtelAttributeKey = other.OtelAttributeKey;
      }
      if (other.Type != global::Routeiq.V1.Telemetry.AttributeType.Unspecified) {
        Type = other.Type;
      }
      if (other.Required != false) {
        Required = other.Required;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ProtoFieldPath = input.ReadString();
            break;
          }
          case 18: {
            OtelAttributeKey = input.ReadString();
            break;
          }
          case 24: {
            Type = (global::Routeiq.V1.Telemetry.AttributeType) input.ReadEnum();
            break;
          }
          case 32: {
            Required = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ProtoFieldPath = input.ReadString();
            break;
          }
          case 18: {
            OtelAttributeKey = input.ReadString();
            break;
          }
          case 24: {
            Type = (global::Routeiq.V1.Telemetry.AttributeType) input.ReadEnum();
            break;
          }
          case 32: {
            Required = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ConventionRegistry is the root message for conventions/telemetry.yaml.
  /// Every AgentEvent field that appears on the wire must have an entry here.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ConventionRegistry : pb::IMessage<ConventionRegistry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConventionRegistry> _parser = new pb::MessageParser<ConventionRegistry>(() => new ConventionRegistry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConventionRegistry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Telemetry.ConventionsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConventionRegistry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConventionRegistry(ConventionRegistry other) : this() {
      conventions_ = other.conventions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConventionRegistry Clone() {
      return new ConventionRegistry(this);
    }

    /// <summary>Field number for the "conventions" field.</summary>
    public const int ConventionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Routeiq.V1.Telemetry.SemanticConvention> _repeated_conventions_codec
        = pb::FieldCodec.ForMessage(10, global::Routeiq.V1.Telemetry.SemanticConvention.Parser);
    private readonly pbc::RepeatedField<global::Routeiq.V1.Telemetry.SemanticConvention> conventions_ = new pbc::RepeatedField<global::Routeiq.V1.Telemetry.SemanticConvention>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Routeiq.V1.Telemetry.SemanticConvention> Conventions {
      get { return conventions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConventionRegistry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConventionRegistry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!conventions_.Equals(other.conventions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= conventions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      conventions_.WriteTo(output, _repeated_conventions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      conventions_.WriteTo(ref output, _repeated_conventions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += conventions_.CalculateSize(_repeated_conventions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConventionRegistry other) {
      if (other == null) {
        return;
      }
      conventions_.Add(other.conventions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            conventions_.AddEntriesFrom(input, _repeated_conventions_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            conventions_.AddEntriesFrom(ref input, _repeated_conventions_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
