// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: routeiq/v1/telemetry/entities.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Routeiq.V1.Telemetry {

  /// <summary>Holder for reflection information generated from routeiq/v1/telemetry/entities.proto</summary>
  public static partial class EntitiesReflection {

    #region Descriptor
    /// <summary>File descriptor for routeiq/v1/telemetry/entities.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntitiesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNyb3V0ZWlxL3YxL3RlbGVtZXRyeS9lbnRpdGllcy5wcm90bxIUcm91dGVp",
            "cS52MS50ZWxlbWV0cnkqeAoQQ29tcGxldGlvblN0YXR1cxIhCh1DT01QTEVU",
            "SU9OX1NUQVRVU19VTlNQRUNJRklFRBAAEgsKB1NVQ0NFU1MQARILCgdGQUlM",
            "VVJFEAISCwoHUEFSVElBTBADEg0KCUNBTkNFTExFRBAEEgsKB1RJTUVPVVQQ",
            "BSrSAQoPRmFpbHVyZUNhdGVnb3J5EiAKHEZBSUxVUkVfQ0FURUdPUllfVU5T",
            "UEVDSUZJRUQQABIOCgpUT09MX0VSUk9SEAESDwoLTU9ERUxfRVJST1IQAhIQ",
            "CgxQT0xJQ1lfQkxPQ0sQAxIRCg1MT09QX0RFVEVDVEVEEAQSFAoQVElNRU9V",
            "VF9FWENFRURFRBAFEhMKD0hVTUFOX0NBTkNFTExFRBAGEhYKElJFU09VUkNF",
            "X0VYSEFVU1RFRBAHEhQKEENPTlRFWFRfT1ZFUkZMT1cQCCpiCgxBdXRvbm9t",
            "eU1vZGUSHQoZQVVUT05PTVlfTU9ERV9VTlNQRUNJRklFRBAAEg4KClNVUEVS",
            "VklTRUQQARITCg9TRU1JX0FVVE9OT01PVVMQAhIOCgpBVVRPTk9NT1VTEAMq",
            "UgoIUmlza1RpZXISGQoVUklTS19USUVSX1VOU1BFQ0lGSUVEEAASBwoDTE9X",
            "EAESCgoGTUVESVVNEAISCAoESElHSBADEgwKCENSSVRJQ0FMEAQqbgoPUGVy",
            "bWlzc2lvbkxldmVsEiAKHFBFUk1JU1NJT05fTEVWRUxfVU5TUEVDSUZJRUQQ",
            "ABINCglSRUFEX09OTFkQARIOCgpSRUFEX1dSSVRFEAISDgoKUFJJVklMRUdF",
            "RBADEgoKBlNZU1RFTRAEKogBChBUb29sUmVzdWx0U3RhdHVzEiIKHlRPT0xf",
            "UkVTVUxUX1NUQVRVU19VTlNQRUNJRklFRBAAEhAKDFRPT0xfU1VDQ0VTUxAB",
            "EhAKDFRPT0xfRkFJTFVSRRACEhAKDFRPT0xfVElNRU9VVBADEhoKFlRPT0xf",
            "UEVSTUlTU0lPTl9ERU5JRUQQBCp5Cg1BdHRyaWJ1dGVUeXBlEh4KGkFUVFJJ",
            "QlVURV9UWVBFX1VOU1BFQ0lGSUVEEAASCgoGU1RSSU5HEAESCQoFSU5UNjQQ",
            "AhIKCgZET1VCTEUQAxIICgRCT09MEAQSCQoFQllURVMQBRIQCgxTVFJJTkdf",
            "QVJSQVkQBkKZAQoyYnVpbGQuYnVmLmdlbi5zc2ZvcmdlLnJvdXRlaXEucm91",
            "dGVpcS52MS50ZWxlbWV0cnlCDUVudGl0aWVzUHJvdG9aVGJ1Zi5idWlsZC9n",
            "ZW4vZ28vc3Nmb3JnZS9yb3V0ZWlxL3Byb3RvY29sYnVmZmVycy9nby9yb3V0",
            "ZWlxL3YxL3RlbGVtZXRyeTt0ZWxlbWV0cnl2MWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Routeiq.V1.Telemetry.CompletionStatus), typeof(global::Routeiq.V1.Telemetry.FailureCategory), typeof(global::Routeiq.V1.Telemetry.AutonomyMode), typeof(global::Routeiq.V1.Telemetry.RiskTier), typeof(global::Routeiq.V1.Telemetry.PermissionLevel), typeof(global::Routeiq.V1.Telemetry.ToolResultStatus), typeof(global::Routeiq.V1.Telemetry.AttributeType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CompletionStatus {
    [pbr::OriginalName("COMPLETION_STATUS_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("SUCCESS")] Success = 1,
    [pbr::OriginalName("FAILURE")] Failure = 2,
    [pbr::OriginalName("PARTIAL")] Partial = 3,
    [pbr::OriginalName("CANCELLED")] Cancelled = 4,
    [pbr::OriginalName("TIMEOUT")] Timeout = 5,
  }

  public enum FailureCategory {
    [pbr::OriginalName("FAILURE_CATEGORY_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("TOOL_ERROR")] ToolError = 1,
    [pbr::OriginalName("MODEL_ERROR")] ModelError = 2,
    [pbr::OriginalName("POLICY_BLOCK")] PolicyBlock = 3,
    [pbr::OriginalName("LOOP_DETECTED")] LoopDetected = 4,
    [pbr::OriginalName("TIMEOUT_EXCEEDED")] TimeoutExceeded = 5,
    [pbr::OriginalName("HUMAN_CANCELLED")] HumanCancelled = 6,
    [pbr::OriginalName("RESOURCE_EXHAUSTED")] ResourceExhausted = 7,
    [pbr::OriginalName("CONTEXT_OVERFLOW")] ContextOverflow = 8,
  }

  public enum AutonomyMode {
    [pbr::OriginalName("AUTONOMY_MODE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("SUPERVISED")] Supervised = 1,
    [pbr::OriginalName("SEMI_AUTONOMOUS")] SemiAutonomous = 2,
    [pbr::OriginalName("AUTONOMOUS")] Autonomous = 3,
  }

  public enum RiskTier {
    [pbr::OriginalName("RISK_TIER_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("LOW")] Low = 1,
    [pbr::OriginalName("MEDIUM")] Medium = 2,
    [pbr::OriginalName("HIGH")] High = 3,
    [pbr::OriginalName("CRITICAL")] Critical = 4,
  }

  public enum PermissionLevel {
    [pbr::OriginalName("PERMISSION_LEVEL_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("READ_ONLY")] ReadOnly = 1,
    [pbr::OriginalName("READ_WRITE")] ReadWrite = 2,
    [pbr::OriginalName("PRIVILEGED")] Privileged = 3,
    [pbr::OriginalName("SYSTEM")] System = 4,
  }

  public enum ToolResultStatus {
    [pbr::OriginalName("TOOL_RESULT_STATUS_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("TOOL_SUCCESS")] ToolSuccess = 1,
    [pbr::OriginalName("TOOL_FAILURE")] ToolFailure = 2,
    [pbr::OriginalName("TOOL_TIMEOUT")] ToolTimeout = 3,
    [pbr::OriginalName("TOOL_PERMISSION_DENIED")] ToolPermissionDenied = 4,
  }

  public enum AttributeType {
    [pbr::OriginalName("ATTRIBUTE_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("STRING")] String = 1,
    [pbr::OriginalName("INT64")] Int64 = 2,
    [pbr::OriginalName("DOUBLE")] Double = 3,
    [pbr::OriginalName("BOOL")] Bool = 4,
    [pbr::OriginalName("BYTES")] Bytes = 5,
    [pbr::OriginalName("STRING_ARRAY")] StringArray = 6,
  }

  #endregion

}

#endregion Designer generated code
