// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: routeiq/v1/control/guardrail.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Routeiq.V1.Control {

  /// <summary>Holder for reflection information generated from routeiq/v1/control/guardrail.proto</summary>
  public static partial class GuardrailReflection {

    #region Descriptor
    /// <summary>File descriptor for routeiq/v1/control/guardrail.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GuardrailReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJyb3V0ZWlxL3YxL2NvbnRyb2wvZ3VhcmRyYWlsLnByb3RvEhJyb3V0ZWlx",
            "LnYxLmNvbnRyb2waI3JvdXRlaXEvdjEvdGVsZW1ldHJ5L2VudGl0aWVzLnBy",
            "b3RvItQBChVDaGVja0d1YXJkcmFpbFJlcXVlc3QSHQoKc2Vzc2lvbl9pZBgB",
            "IAEoCVIJc2Vzc2lvbklkEicKD3Byb3Bvc2VkX2FjdGlvbhgCIAEoCVIOcHJv",
            "cG9zZWRBY3Rpb24SUAoQcGVybWlzc2lvbl9sZXZlbBgDIAEoDjIlLnJvdXRl",
            "aXEudjEudGVsZW1ldHJ5LlBlcm1pc3Npb25MZXZlbFIPcGVybWlzc2lvbkxl",
            "dmVsEiEKDHJpc2tfY29udGV4dBgEIAEoCVILcmlza0NvbnRleHQiogEKFkNo",
            "ZWNrR3VhcmRyYWlsUmVzcG9uc2USPgoHdmVyZGljdBgBIAEoDjIkLnJvdXRl",
            "aXEudjEuY29udHJvbC5HdWFyZHJhaWxWZXJkaWN0Ugd2ZXJkaWN0EhYKBnJl",
            "YXNvbhgCIAEoCVIGcmVhc29uEjAKFHBvbGljeV9pZHNfdHJpZ2dlcmVkGAMg",
            "AygJUhJwb2xpY3lJZHNUcmlnZ2VyZWQiggEKFVJlZ2lzdGVyUG9saWN5UmVx",
            "dWVzdBIbCglwb2xpY3lfaWQYASABKAlSCHBvbGljeUlkEiUKDmJ1bmRsZV92",
            "ZXJzaW9uGAIgASgJUg1idW5kbGVWZXJzaW9uEiUKDnBvbGljeV9jb250ZW50",
            "GAMgASgMUg1wb2xpY3lDb250ZW50ImEKFlJlZ2lzdGVyUG9saWN5UmVzcG9u",
            "c2USGgoIYWNjZXB0ZWQYASABKAhSCGFjY2VwdGVkEisKEWVmZmVjdGl2ZV92",
            "ZXJzaW9uGAIgASgJUhBlZmZlY3RpdmVWZXJzaW9uKmEKEEd1YXJkcmFpbFZl",
            "cmRpY3QSIQodR1VBUkRSQUlMX1ZFUkRJQ1RfVU5TUEVDSUZJRUQQABIJCgVB",
            "TExPVxABEgkKBUJMT0NLEAISFAoQUkVRVUlSRV9BUFBST1ZBTBADMuQBChBH",
            "dWFyZHJhaWxTZXJ2aWNlEmcKDkNoZWNrR3VhcmRyYWlsEikucm91dGVpcS52",
            "MS5jb250cm9sLkNoZWNrR3VhcmRyYWlsUmVxdWVzdBoqLnJvdXRlaXEudjEu",
            "Y29udHJvbC5DaGVja0d1YXJkcmFpbFJlc3BvbnNlEmcKDlJlZ2lzdGVyUG9s",
            "aWN5Eikucm91dGVpcS52MS5jb250cm9sLlJlZ2lzdGVyUG9saWN5UmVxdWVz",
            "dBoqLnJvdXRlaXEudjEuY29udHJvbC5SZWdpc3RlclBvbGljeVJlc3BvbnNl",
            "QpQBCjBidWlsZC5idWYuZ2VuLnNzZm9yZ2Uucm91dGVpcS5yb3V0ZWlxLnYx",
            "LmNvbnRyb2xCDkd1YXJkcmFpbFByb3RvWlBidWYuYnVpbGQvZ2VuL2dvL3Nz",
            "Zm9yZ2Uvcm91dGVpcS9wcm90b2NvbGJ1ZmZlcnMvZ28vcm91dGVpcS92MS9j",
            "b250cm9sO2NvbnRyb2x2MWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Routeiq.V1.Telemetry.EntitiesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Routeiq.V1.Control.GuardrailVerdict), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Control.CheckGuardrailRequest), global::Routeiq.V1.Control.CheckGuardrailRequest.Parser, new[]{ "SessionId", "ProposedAction", "PermissionLevel", "RiskContext" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Control.CheckGuardrailResponse), global::Routeiq.V1.Control.CheckGuardrailResponse.Parser, new[]{ "Verdict", "Reason", "PolicyIdsTriggered" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Control.RegisterPolicyRequest), global::Routeiq.V1.Control.RegisterPolicyRequest.Parser, new[]{ "PolicyId", "BundleVersion", "PolicyContent" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Control.RegisterPolicyResponse), global::Routeiq.V1.Control.RegisterPolicyResponse.Parser, new[]{ "Accepted", "EffectiveVersion" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GuardrailVerdict {
    [pbr::OriginalName("GUARDRAIL_VERDICT_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("ALLOW")] Allow = 1,
    [pbr::OriginalName("BLOCK")] Block = 2,
    [pbr::OriginalName("REQUIRE_APPROVAL")] RequireApproval = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CheckGuardrailRequest : pb::IMessage<CheckGuardrailRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CheckGuardrailRequest> _parser = new pb::MessageParser<CheckGuardrailRequest>(() => new CheckGuardrailRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CheckGuardrailRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Control.GuardrailReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CheckGuardrailRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CheckGuardrailRequest(CheckGuardrailRequest other) : this() {
      sessionId_ = other.sessionId_;
      proposedAction_ = other.proposedAction_;
      permissionLevel_ = other.permissionLevel_;
      riskContext_ = other.riskContext_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CheckGuardrailRequest Clone() {
      return new CheckGuardrailRequest(this);
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 1;
    private string sessionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "proposed_action" field.</summary>
    public const int ProposedActionFieldNumber = 2;
    private string proposedAction_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProposedAction {
      get { return proposedAction_; }
      set {
        proposedAction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "permission_level" field.</summary>
    public const int PermissionLevelFieldNumber = 3;
    private global::Routeiq.V1.Telemetry.PermissionLevel permissionLevel_ = global::Routeiq.V1.Telemetry.PermissionLevel.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Routeiq.V1.Telemetry.PermissionLevel PermissionLevel {
      get { return permissionLevel_; }
      set {
        permissionLevel_ = value;
      }
    }

    /// <summary>Field number for the "risk_context" field.</summary>
    public const int RiskContextFieldNumber = 4;
    private string riskContext_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RiskContext {
      get { return riskContext_; }
      set {
        riskContext_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CheckGuardrailRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CheckGuardrailRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SessionId != other.SessionId) return false;
      if (ProposedAction != other.ProposedAction) return false;
      if (PermissionLevel != other.PermissionLevel) return false;
      if (RiskContext != other.RiskContext) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (ProposedAction.Length != 0) hash ^= ProposedAction.GetHashCode();
      if (PermissionLevel != global::Routeiq.V1.Telemetry.PermissionLevel.Unspecified) hash ^= PermissionLevel.GetHashCode();
      if (RiskContext.Length != 0) hash ^= RiskContext.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SessionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionId);
      }
      if (ProposedAction.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ProposedAction);
      }
      if (PermissionLevel != global::Routeiq.V1.Telemetry.PermissionLevel.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) PermissionLevel);
      }
      if (RiskContext.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RiskContext);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SessionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionId);
      }
      if (ProposedAction.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ProposedAction);
      }
      if (PermissionLevel != global::Routeiq.V1.Telemetry.PermissionLevel.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) PermissionLevel);
      }
      if (RiskContext.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RiskContext);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (ProposedAction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProposedAction);
      }
      if (PermissionLevel != global::Routeiq.V1.Telemetry.PermissionLevel.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PermissionLevel);
      }
      if (RiskContext.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RiskContext);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CheckGuardrailRequest other) {
      if (other == null) {
        return;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      if (other.ProposedAction.Length != 0) {
        ProposedAction = other.ProposedAction;
      }
      if (other.PermissionLevel != global::Routeiq.V1.Telemetry.PermissionLevel.Unspecified) {
        PermissionLevel = other.PermissionLevel;
      }
      if (other.RiskContext.Length != 0) {
        RiskContext = other.RiskContext;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SessionId = input.ReadString();
            break;
          }
          case 18: {
            ProposedAction = input.ReadString();
            break;
          }
          case 24: {
            PermissionLevel = (global::Routeiq.V1.Telemetry.PermissionLevel) input.ReadEnum();
            break;
          }
          case 34: {
            RiskContext = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SessionId = input.ReadString();
            break;
          }
          case 18: {
            ProposedAction = input.ReadString();
            break;
          }
          case 24: {
            PermissionLevel = (global::Routeiq.V1.Telemetry.PermissionLevel) input.ReadEnum();
            break;
          }
          case 34: {
            RiskContext = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CheckGuardrailResponse : pb::IMessage<CheckGuardrailResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CheckGuardrailResponse> _parser = new pb::MessageParser<CheckGuardrailResponse>(() => new CheckGuardrailResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CheckGuardrailResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Control.GuardrailReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CheckGuardrailResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CheckGuardrailResponse(CheckGuardrailResponse other) : this() {
      verdict_ = other.verdict_;
      reason_ = other.reason_;
      policyIdsTriggered_ = other.policyIdsTriggered_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CheckGuardrailResponse Clone() {
      return new CheckGuardrailResponse(this);
    }

    /// <summary>Field number for the "verdict" field.</summary>
    public const int VerdictFieldNumber = 1;
    private global::Routeiq.V1.Control.GuardrailVerdict verdict_ = global::Routeiq.V1.Control.GuardrailVerdict.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Routeiq.V1.Control.GuardrailVerdict Verdict {
      get { return verdict_; }
      set {
        verdict_ = value;
      }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 2;
    private string reason_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Reason {
      get { return reason_; }
      set {
        reason_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "policy_ids_triggered" field.</summary>
    public const int PolicyIdsTriggeredFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_policyIdsTriggered_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> policyIdsTriggered_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> PolicyIdsTriggered {
      get { return policyIdsTriggered_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CheckGuardrailResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CheckGuardrailResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Verdict != other.Verdict) return false;
      if (Reason != other.Reason) return false;
      if(!policyIdsTriggered_.Equals(other.policyIdsTriggered_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Verdict != global::Routeiq.V1.Control.GuardrailVerdict.Unspecified) hash ^= Verdict.GetHashCode();
      if (Reason.Length != 0) hash ^= Reason.GetHashCode();
      hash ^= policyIdsTriggered_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Verdict != global::Routeiq.V1.Control.GuardrailVerdict.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Verdict);
      }
      if (Reason.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Reason);
      }
      policyIdsTriggered_.WriteTo(output, _repeated_policyIdsTriggered_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Verdict != global::Routeiq.V1.Control.GuardrailVerdict.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Verdict);
      }
      if (Reason.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Reason);
      }
      policyIdsTriggered_.WriteTo(ref output, _repeated_policyIdsTriggered_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Verdict != global::Routeiq.V1.Control.GuardrailVerdict.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Verdict);
      }
      if (Reason.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reason);
      }
      size += policyIdsTriggered_.CalculateSize(_repeated_policyIdsTriggered_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CheckGuardrailResponse other) {
      if (other == null) {
        return;
      }
      if (other.Verdict != global::Routeiq.V1.Control.GuardrailVerdict.Unspecified) {
        Verdict = other.Verdict;
      }
      if (other.Reason.Length != 0) {
        Reason = other.Reason;
      }
      policyIdsTriggered_.Add(other.policyIdsTriggered_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Verdict = (global::Routeiq.V1.Control.GuardrailVerdict) input.ReadEnum();
            break;
          }
          case 18: {
            Reason = input.ReadString();
            break;
          }
          case 26: {
            policyIdsTriggered_.AddEntriesFrom(input, _repeated_policyIdsTriggered_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Verdict = (global::Routeiq.V1.Control.GuardrailVerdict) input.ReadEnum();
            break;
          }
          case 18: {
            Reason = input.ReadString();
            break;
          }
          case 26: {
            policyIdsTriggered_.AddEntriesFrom(ref input, _repeated_policyIdsTriggered_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RegisterPolicyRequest : pb::IMessage<RegisterPolicyRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisterPolicyRequest> _parser = new pb::MessageParser<RegisterPolicyRequest>(() => new RegisterPolicyRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisterPolicyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Control.GuardrailReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterPolicyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterPolicyRequest(RegisterPolicyRequest other) : this() {
      policyId_ = other.policyId_;
      bundleVersion_ = other.bundleVersion_;
      policyContent_ = other.policyContent_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterPolicyRequest Clone() {
      return new RegisterPolicyRequest(this);
    }

    /// <summary>Field number for the "policy_id" field.</summary>
    public const int PolicyIdFieldNumber = 1;
    private string policyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PolicyId {
      get { return policyId_; }
      set {
        policyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bundle_version" field.</summary>
    public const int BundleVersionFieldNumber = 2;
    private string bundleVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BundleVersion {
      get { return bundleVersion_; }
      set {
        bundleVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "policy_content" field.</summary>
    public const int PolicyContentFieldNumber = 3;
    private pb::ByteString policyContent_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString PolicyContent {
      get { return policyContent_; }
      set {
        policyContent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisterPolicyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisterPolicyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PolicyId != other.PolicyId) return false;
      if (BundleVersion != other.BundleVersion) return false;
      if (PolicyContent != other.PolicyContent) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PolicyId.Length != 0) hash ^= PolicyId.GetHashCode();
      if (BundleVersion.Length != 0) hash ^= BundleVersion.GetHashCode();
      if (PolicyContent.Length != 0) hash ^= PolicyContent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PolicyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PolicyId);
      }
      if (BundleVersion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BundleVersion);
      }
      if (PolicyContent.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(PolicyContent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PolicyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PolicyId);
      }
      if (BundleVersion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BundleVersion);
      }
      if (PolicyContent.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(PolicyContent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PolicyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PolicyId);
      }
      if (BundleVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BundleVersion);
      }
      if (PolicyContent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PolicyContent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisterPolicyRequest other) {
      if (other == null) {
        return;
      }
      if (other.PolicyId.Length != 0) {
        PolicyId = other.PolicyId;
      }
      if (other.BundleVersion.Length != 0) {
        BundleVersion = other.BundleVersion;
      }
      if (other.PolicyContent.Length != 0) {
        PolicyContent = other.PolicyContent;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PolicyId = input.ReadString();
            break;
          }
          case 18: {
            BundleVersion = input.ReadString();
            break;
          }
          case 26: {
            PolicyContent = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PolicyId = input.ReadString();
            break;
          }
          case 18: {
            BundleVersion = input.ReadString();
            break;
          }
          case 26: {
            PolicyContent = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RegisterPolicyResponse : pb::IMessage<RegisterPolicyResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisterPolicyResponse> _parser = new pb::MessageParser<RegisterPolicyResponse>(() => new RegisterPolicyResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisterPolicyResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Control.GuardrailReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterPolicyResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterPolicyResponse(RegisterPolicyResponse other) : this() {
      accepted_ = other.accepted_;
      effectiveVersion_ = other.effectiveVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterPolicyResponse Clone() {
      return new RegisterPolicyResponse(this);
    }

    /// <summary>Field number for the "accepted" field.</summary>
    public const int AcceptedFieldNumber = 1;
    private bool accepted_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Accepted {
      get { return accepted_; }
      set {
        accepted_ = value;
      }
    }

    /// <summary>Field number for the "effective_version" field.</summary>
    public const int EffectiveVersionFieldNumber = 2;
    private string effectiveVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EffectiveVersion {
      get { return effectiveVersion_; }
      set {
        effectiveVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisterPolicyResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisterPolicyResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Accepted != other.Accepted) return false;
      if (EffectiveVersion != other.EffectiveVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Accepted != false) hash ^= Accepted.GetHashCode();
      if (EffectiveVersion.Length != 0) hash ^= EffectiveVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Accepted != false) {
        output.WriteRawTag(8);
        output.WriteBool(Accepted);
      }
      if (EffectiveVersion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EffectiveVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Accepted != false) {
        output.WriteRawTag(8);
        output.WriteBool(Accepted);
      }
      if (EffectiveVersion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EffectiveVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Accepted != false) {
        size += 1 + 1;
      }
      if (EffectiveVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EffectiveVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisterPolicyResponse other) {
      if (other == null) {
        return;
      }
      if (other.Accepted != false) {
        Accepted = other.Accepted;
      }
      if (other.EffectiveVersion.Length != 0) {
        EffectiveVersion = other.EffectiveVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Accepted = input.ReadBool();
            break;
          }
          case 18: {
            EffectiveVersion = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Accepted = input.ReadBool();
            break;
          }
          case 18: {
            EffectiveVersion = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
