// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: routeiq/v1/insights/interventions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Routeiq.V1.Insights {

  /// <summary>Holder for reflection information generated from routeiq/v1/insights/interventions.proto</summary>
  public static partial class InterventionsReflection {

    #region Descriptor
    /// <summary>File descriptor for routeiq/v1/insights/interventions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InterventionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cidyb3V0ZWlxL3YxL2luc2lnaHRzL2ludGVydmVudGlvbnMucHJvdG8SE3Jv",
            "dXRlaXEudjEuaW5zaWdodHMaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAu",
            "cHJvdG8aIHJvdXRlaXEvdjEvaW5zaWdodHMvYWxlcnRzLnByb3RvIusCChpJ",
            "bnRlcnZlbnRpb25SZWNvbW1lbmRhdGlvbhIOCgJpZBgBIAEoCVICaWQSIgoN",
            "YWxlcnRfcnVsZV9pZBgCIAEoCVILYWxlcnRSdWxlSWQSGwoJbWV0cmljX2lk",
            "GAMgASgJUghtZXRyaWNJZBI+CgZhY3Rpb24YBCABKA4yJi5yb3V0ZWlxLnYx",
            "Lmluc2lnaHRzLlJlY29tbWVuZGVkQWN0aW9uUgZhY3Rpb24SHAoJcmF0aW9u",
            "YWxlGAUgASgJUglyYXRpb25hbGUSHgoKY29uZmlkZW5jZRgGIAEoAVIKY29u",
            "ZmlkZW5jZRI9CgxnZW5lcmF0ZWRfYXQYByABKAsyGi5nb29nbGUucHJvdG9i",
            "dWYuVGltZXN0YW1wUgtnZW5lcmF0ZWRBdBI/CgZzdGF0dXMYCCABKA4yJy5y",
            "b3V0ZWlxLnYxLmluc2lnaHRzLkludGVydmVudGlvblN0YXR1c1IGc3RhdHVz",
            "Km8KEkludGVydmVudGlvblN0YXR1cxIjCh9JTlRFUlZFTlRJT05fU1RBVFVT",
            "X1VOU1BFQ0lGSUVEEAASCwoHUEVORElORxABEgsKB0FQUExJRUQQAhINCglE",
            "SVNNSVNTRUQQAxILCgdFWFBJUkVEEARCmwEKMWJ1aWxkLmJ1Zi5nZW4uc3Nm",
            "b3JnZS5yb3V0ZWlxLnJvdXRlaXEudjEuaW5zaWdodHNCEkludGVydmVudGlv",
            "bnNQcm90b1pSYnVmLmJ1aWxkL2dlbi9nby9zc2ZvcmdlL3JvdXRlaXEvcHJv",
            "dG9jb2xidWZmZXJzL2dvL3JvdXRlaXEvdjEvaW5zaWdodHM7aW5zaWdodHN2",
            "MWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Routeiq.V1.Insights.AlertsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Routeiq.V1.Insights.InterventionStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Insights.InterventionRecommendation), global::Routeiq.V1.Insights.InterventionRecommendation.Parser, new[]{ "Id", "AlertRuleId", "MetricId", "Action", "Rationale", "Confidence", "GeneratedAt", "Status" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum InterventionStatus {
    [pbr::OriginalName("INTERVENTION_STATUS_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("PENDING")] Pending = 1,
    [pbr::OriginalName("APPLIED")] Applied = 2,
    [pbr::OriginalName("DISMISSED")] Dismissed = 3,
    [pbr::OriginalName("EXPIRED")] Expired = 4,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class InterventionRecommendation : pb::IMessage<InterventionRecommendation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InterventionRecommendation> _parser = new pb::MessageParser<InterventionRecommendation>(() => new InterventionRecommendation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InterventionRecommendation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Insights.InterventionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InterventionRecommendation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InterventionRecommendation(InterventionRecommendation other) : this() {
      id_ = other.id_;
      alertRuleId_ = other.alertRuleId_;
      metricId_ = other.metricId_;
      action_ = other.action_;
      rationale_ = other.rationale_;
      confidence_ = other.confidence_;
      generatedAt_ = other.generatedAt_ != null ? other.generatedAt_.Clone() : null;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InterventionRecommendation Clone() {
      return new InterventionRecommendation(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "alert_rule_id" field.</summary>
    public const int AlertRuleIdFieldNumber = 2;
    private string alertRuleId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AlertRuleId {
      get { return alertRuleId_; }
      set {
        alertRuleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "metric_id" field.</summary>
    public const int MetricIdFieldNumber = 3;
    private string metricId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MetricId {
      get { return metricId_; }
      set {
        metricId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 4;
    private global::Routeiq.V1.Insights.RecommendedAction action_ = global::Routeiq.V1.Insights.RecommendedAction.ActionUnspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Routeiq.V1.Insights.RecommendedAction Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    /// <summary>Field number for the "rationale" field.</summary>
    public const int RationaleFieldNumber = 5;
    private string rationale_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Rationale {
      get { return rationale_; }
      set {
        rationale_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "confidence" field.</summary>
    public const int ConfidenceFieldNumber = 6;
    private double confidence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Confidence {
      get { return confidence_; }
      set {
        confidence_ = value;
      }
    }

    /// <summary>Field number for the "generated_at" field.</summary>
    public const int GeneratedAtFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp generatedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp GeneratedAt {
      get { return generatedAt_; }
      set {
        generatedAt_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 8;
    private global::Routeiq.V1.Insights.InterventionStatus status_ = global::Routeiq.V1.Insights.InterventionStatus.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Routeiq.V1.Insights.InterventionStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InterventionRecommendation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InterventionRecommendation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (AlertRuleId != other.AlertRuleId) return false;
      if (MetricId != other.MetricId) return false;
      if (Action != other.Action) return false;
      if (Rationale != other.Rationale) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Confidence, other.Confidence)) return false;
      if (!object.Equals(GeneratedAt, other.GeneratedAt)) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (AlertRuleId.Length != 0) hash ^= AlertRuleId.GetHashCode();
      if (MetricId.Length != 0) hash ^= MetricId.GetHashCode();
      if (Action != global::Routeiq.V1.Insights.RecommendedAction.ActionUnspecified) hash ^= Action.GetHashCode();
      if (Rationale.Length != 0) hash ^= Rationale.GetHashCode();
      if (Confidence != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Confidence);
      if (generatedAt_ != null) hash ^= GeneratedAt.GetHashCode();
      if (Status != global::Routeiq.V1.Insights.InterventionStatus.Unspecified) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (AlertRuleId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AlertRuleId);
      }
      if (MetricId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MetricId);
      }
      if (Action != global::Routeiq.V1.Insights.RecommendedAction.ActionUnspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Action);
      }
      if (Rationale.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Rationale);
      }
      if (Confidence != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Confidence);
      }
      if (generatedAt_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(GeneratedAt);
      }
      if (Status != global::Routeiq.V1.Insights.InterventionStatus.Unspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (AlertRuleId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AlertRuleId);
      }
      if (MetricId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MetricId);
      }
      if (Action != global::Routeiq.V1.Insights.RecommendedAction.ActionUnspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Action);
      }
      if (Rationale.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Rationale);
      }
      if (Confidence != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Confidence);
      }
      if (generatedAt_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(GeneratedAt);
      }
      if (Status != global::Routeiq.V1.Insights.InterventionStatus.Unspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (AlertRuleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AlertRuleId);
      }
      if (MetricId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MetricId);
      }
      if (Action != global::Routeiq.V1.Insights.RecommendedAction.ActionUnspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Action);
      }
      if (Rationale.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Rationale);
      }
      if (Confidence != 0D) {
        size += 1 + 8;
      }
      if (generatedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GeneratedAt);
      }
      if (Status != global::Routeiq.V1.Insights.InterventionStatus.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InterventionRecommendation other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.AlertRuleId.Length != 0) {
        AlertRuleId = other.AlertRuleId;
      }
      if (other.MetricId.Length != 0) {
        MetricId = other.MetricId;
      }
      if (other.Action != global::Routeiq.V1.Insights.RecommendedAction.ActionUnspecified) {
        Action = other.Action;
      }
      if (other.Rationale.Length != 0) {
        Rationale = other.Rationale;
      }
      if (other.Confidence != 0D) {
        Confidence = other.Confidence;
      }
      if (other.generatedAt_ != null) {
        if (generatedAt_ == null) {
          GeneratedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        GeneratedAt.MergeFrom(other.GeneratedAt);
      }
      if (other.Status != global::Routeiq.V1.Insights.InterventionStatus.Unspecified) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            AlertRuleId = input.ReadString();
            break;
          }
          case 26: {
            MetricId = input.ReadString();
            break;
          }
          case 32: {
            Action = (global::Routeiq.V1.Insights.RecommendedAction) input.ReadEnum();
            break;
          }
          case 42: {
            Rationale = input.ReadString();
            break;
          }
          case 49: {
            Confidence = input.ReadDouble();
            break;
          }
          case 58: {
            if (generatedAt_ == null) {
              GeneratedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(GeneratedAt);
            break;
          }
          case 64: {
            Status = (global::Routeiq.V1.Insights.InterventionStatus) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            AlertRuleId = input.ReadString();
            break;
          }
          case 26: {
            MetricId = input.ReadString();
            break;
          }
          case 32: {
            Action = (global::Routeiq.V1.Insights.RecommendedAction) input.ReadEnum();
            break;
          }
          case 42: {
            Rationale = input.ReadString();
            break;
          }
          case 49: {
            Confidence = input.ReadDouble();
            break;
          }
          case 58: {
            if (generatedAt_ == null) {
              GeneratedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(GeneratedAt);
            break;
          }
          case 64: {
            Status = (global::Routeiq.V1.Insights.InterventionStatus) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
