// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: routeiq/v1/control/intervention.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Routeiq.V1.Control {

  /// <summary>Holder for reflection information generated from routeiq/v1/control/intervention.proto</summary>
  public static partial class InterventionReflection {

    #region Descriptor
    /// <summary>File descriptor for routeiq/v1/control/intervention.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InterventionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVyb3V0ZWlxL3YxL2NvbnRyb2wvaW50ZXJ2ZW50aW9uLnByb3RvEhJyb3V0",
            "ZWlxLnYxLmNvbnRyb2waH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJv",
            "dG8aI3JvdXRlaXEvdjEvdGVsZW1ldHJ5L2VudGl0aWVzLnByb3RvItQBChpU",
            "cmlnZ2VySW50ZXJ2ZW50aW9uUmVxdWVzdBIdCgpzZXNzaW9uX2lkGAEgASgJ",
            "UglzZXNzaW9uSWQSOAoEa2luZBgCIAEoDjIkLnJvdXRlaXEudjEuY29udHJv",
            "bC5JbnRlcnZlbnRpb25LaW5kUgRraW5kEhYKBnJlYXNvbhgDIAEoCVIGcmVh",
            "c29uEkUKDGRvd25ncmFkZV90bxgEIAEoDjIiLnJvdXRlaXEudjEudGVsZW1l",
            "dHJ5LkF1dG9ub215TW9kZVILZG93bmdyYWRlVG8imwEKG1RyaWdnZXJJbnRl",
            "cnZlbnRpb25SZXNwb25zZRInCg9pbnRlcnZlbnRpb25faWQYASABKAlSDmlu",
            "dGVydmVudGlvbklkEhgKB2FwcGxpZWQYAiABKAhSB2FwcGxpZWQSOQoKYXBw",
            "bGllZF9hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBSCWFw",
            "cGxpZWRBdCJHChxHZXRJbnRlcnZlbnRpb25TdGF0dXNSZXF1ZXN0EicKD2lu",
            "dGVydmVudGlvbl9pZBgBIAEoCVIOaW50ZXJ2ZW50aW9uSWQimgEKHUdldElu",
            "dGVydmVudGlvblN0YXR1c1Jlc3BvbnNlEicKD2ludGVydmVudGlvbl9pZBgB",
            "IAEoCVIOaW50ZXJ2ZW50aW9uSWQSOAoEa2luZBgCIAEoDjIkLnJvdXRlaXEu",
            "djEuY29udHJvbC5JbnRlcnZlbnRpb25LaW5kUgRraW5kEhYKBmFjdGl2ZRgD",
            "IAEoCFIGYWN0aXZlKo0BChBJbnRlcnZlbnRpb25LaW5kEiEKHUlOVEVSVkVO",
            "VElPTl9LSU5EX1VOU1BFQ0lGSUVEEAASEQoNQ0lSQ1VJVF9CUkVBSxABEgwK",
            "CFJPTExCQUNLEAISFgoSQVVUT05PTVlfRE9XTkdSQURFEAMSDgoKTU9ERUxf",
            "U1dBUBAEEg0KCUhBUkRfU1RPUBAFMosCChNJbnRlcnZlbnRpb25TZXJ2aWNl",
            "EnYKE1RyaWdnZXJJbnRlcnZlbnRpb24SLi5yb3V0ZWlxLnYxLmNvbnRyb2wu",
            "VHJpZ2dlckludGVydmVudGlvblJlcXVlc3QaLy5yb3V0ZWlxLnYxLmNvbnRy",
            "b2wuVHJpZ2dlckludGVydmVudGlvblJlc3BvbnNlEnwKFUdldEludGVydmVu",
            "dGlvblN0YXR1cxIwLnJvdXRlaXEudjEuY29udHJvbC5HZXRJbnRlcnZlbnRp",
            "b25TdGF0dXNSZXF1ZXN0GjEucm91dGVpcS52MS5jb250cm9sLkdldEludGVy",
            "dmVudGlvblN0YXR1c1Jlc3BvbnNlQpcBCjBidWlsZC5idWYuZ2VuLnNzZm9y",
            "Z2Uucm91dGVpcS5yb3V0ZWlxLnYxLmNvbnRyb2xCEUludGVydmVudGlvblBy",
            "b3RvWlBidWYuYnVpbGQvZ2VuL2dvL3NzZm9yZ2Uvcm91dGVpcS9wcm90b2Nv",
            "bGJ1ZmZlcnMvZ28vcm91dGVpcS92MS9jb250cm9sO2NvbnRyb2x2MWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Routeiq.V1.Telemetry.EntitiesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Routeiq.V1.Control.InterventionKind), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Control.TriggerInterventionRequest), global::Routeiq.V1.Control.TriggerInterventionRequest.Parser, new[]{ "SessionId", "Kind", "Reason", "DowngradeTo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Control.TriggerInterventionResponse), global::Routeiq.V1.Control.TriggerInterventionResponse.Parser, new[]{ "InterventionId", "Applied", "AppliedAt" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Control.GetInterventionStatusRequest), global::Routeiq.V1.Control.GetInterventionStatusRequest.Parser, new[]{ "InterventionId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Control.GetInterventionStatusResponse), global::Routeiq.V1.Control.GetInterventionStatusResponse.Parser, new[]{ "InterventionId", "Kind", "Active" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum InterventionKind {
    [pbr::OriginalName("INTERVENTION_KIND_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("CIRCUIT_BREAK")] CircuitBreak = 1,
    [pbr::OriginalName("ROLLBACK")] Rollback = 2,
    [pbr::OriginalName("AUTONOMY_DOWNGRADE")] AutonomyDowngrade = 3,
    [pbr::OriginalName("MODEL_SWAP")] ModelSwap = 4,
    [pbr::OriginalName("HARD_STOP")] HardStop = 5,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TriggerInterventionRequest : pb::IMessage<TriggerInterventionRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TriggerInterventionRequest> _parser = new pb::MessageParser<TriggerInterventionRequest>(() => new TriggerInterventionRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TriggerInterventionRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Control.InterventionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriggerInterventionRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriggerInterventionRequest(TriggerInterventionRequest other) : this() {
      sessionId_ = other.sessionId_;
      kind_ = other.kind_;
      reason_ = other.reason_;
      downgradeTo_ = other.downgradeTo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriggerInterventionRequest Clone() {
      return new TriggerInterventionRequest(this);
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 1;
    private string sessionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 2;
    private global::Routeiq.V1.Control.InterventionKind kind_ = global::Routeiq.V1.Control.InterventionKind.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Routeiq.V1.Control.InterventionKind Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 3;
    private string reason_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Reason {
      get { return reason_; }
      set {
        reason_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "downgrade_to" field.</summary>
    public const int DowngradeToFieldNumber = 4;
    private global::Routeiq.V1.Telemetry.AutonomyMode downgradeTo_ = global::Routeiq.V1.Telemetry.AutonomyMode.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Routeiq.V1.Telemetry.AutonomyMode DowngradeTo {
      get { return downgradeTo_; }
      set {
        downgradeTo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TriggerInterventionRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TriggerInterventionRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SessionId != other.SessionId) return false;
      if (Kind != other.Kind) return false;
      if (Reason != other.Reason) return false;
      if (DowngradeTo != other.DowngradeTo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (Kind != global::Routeiq.V1.Control.InterventionKind.Unspecified) hash ^= Kind.GetHashCode();
      if (Reason.Length != 0) hash ^= Reason.GetHashCode();
      if (DowngradeTo != global::Routeiq.V1.Telemetry.AutonomyMode.Unspecified) hash ^= DowngradeTo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SessionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionId);
      }
      if (Kind != global::Routeiq.V1.Control.InterventionKind.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      if (Reason.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Reason);
      }
      if (DowngradeTo != global::Routeiq.V1.Telemetry.AutonomyMode.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) DowngradeTo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SessionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionId);
      }
      if (Kind != global::Routeiq.V1.Control.InterventionKind.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      if (Reason.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Reason);
      }
      if (DowngradeTo != global::Routeiq.V1.Telemetry.AutonomyMode.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) DowngradeTo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (Kind != global::Routeiq.V1.Control.InterventionKind.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (Reason.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reason);
      }
      if (DowngradeTo != global::Routeiq.V1.Telemetry.AutonomyMode.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DowngradeTo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TriggerInterventionRequest other) {
      if (other == null) {
        return;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      if (other.Kind != global::Routeiq.V1.Control.InterventionKind.Unspecified) {
        Kind = other.Kind;
      }
      if (other.Reason.Length != 0) {
        Reason = other.Reason;
      }
      if (other.DowngradeTo != global::Routeiq.V1.Telemetry.AutonomyMode.Unspecified) {
        DowngradeTo = other.DowngradeTo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SessionId = input.ReadString();
            break;
          }
          case 16: {
            Kind = (global::Routeiq.V1.Control.InterventionKind) input.ReadEnum();
            break;
          }
          case 26: {
            Reason = input.ReadString();
            break;
          }
          case 32: {
            DowngradeTo = (global::Routeiq.V1.Telemetry.AutonomyMode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SessionId = input.ReadString();
            break;
          }
          case 16: {
            Kind = (global::Routeiq.V1.Control.InterventionKind) input.ReadEnum();
            break;
          }
          case 26: {
            Reason = input.ReadString();
            break;
          }
          case 32: {
            DowngradeTo = (global::Routeiq.V1.Telemetry.AutonomyMode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TriggerInterventionResponse : pb::IMessage<TriggerInterventionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TriggerInterventionResponse> _parser = new pb::MessageParser<TriggerInterventionResponse>(() => new TriggerInterventionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TriggerInterventionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Control.InterventionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriggerInterventionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriggerInterventionResponse(TriggerInterventionResponse other) : this() {
      interventionId_ = other.interventionId_;
      applied_ = other.applied_;
      appliedAt_ = other.appliedAt_ != null ? other.appliedAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriggerInterventionResponse Clone() {
      return new TriggerInterventionResponse(this);
    }

    /// <summary>Field number for the "intervention_id" field.</summary>
    public const int InterventionIdFieldNumber = 1;
    private string interventionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InterventionId {
      get { return interventionId_; }
      set {
        interventionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "applied" field.</summary>
    public const int AppliedFieldNumber = 2;
    private bool applied_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Applied {
      get { return applied_; }
      set {
        applied_ = value;
      }
    }

    /// <summary>Field number for the "applied_at" field.</summary>
    public const int AppliedAtFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp appliedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp AppliedAt {
      get { return appliedAt_; }
      set {
        appliedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TriggerInterventionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TriggerInterventionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InterventionId != other.InterventionId) return false;
      if (Applied != other.Applied) return false;
      if (!object.Equals(AppliedAt, other.AppliedAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (InterventionId.Length != 0) hash ^= InterventionId.GetHashCode();
      if (Applied != false) hash ^= Applied.GetHashCode();
      if (appliedAt_ != null) hash ^= AppliedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InterventionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InterventionId);
      }
      if (Applied != false) {
        output.WriteRawTag(16);
        output.WriteBool(Applied);
      }
      if (appliedAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AppliedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InterventionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InterventionId);
      }
      if (Applied != false) {
        output.WriteRawTag(16);
        output.WriteBool(Applied);
      }
      if (appliedAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AppliedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (InterventionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InterventionId);
      }
      if (Applied != false) {
        size += 1 + 1;
      }
      if (appliedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AppliedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TriggerInterventionResponse other) {
      if (other == null) {
        return;
      }
      if (other.InterventionId.Length != 0) {
        InterventionId = other.InterventionId;
      }
      if (other.Applied != false) {
        Applied = other.Applied;
      }
      if (other.appliedAt_ != null) {
        if (appliedAt_ == null) {
          AppliedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        AppliedAt.MergeFrom(other.AppliedAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            InterventionId = input.ReadString();
            break;
          }
          case 16: {
            Applied = input.ReadBool();
            break;
          }
          case 26: {
            if (appliedAt_ == null) {
              AppliedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(AppliedAt);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            InterventionId = input.ReadString();
            break;
          }
          case 16: {
            Applied = input.ReadBool();
            break;
          }
          case 26: {
            if (appliedAt_ == null) {
              AppliedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(AppliedAt);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetInterventionStatusRequest : pb::IMessage<GetInterventionStatusRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetInterventionStatusRequest> _parser = new pb::MessageParser<GetInterventionStatusRequest>(() => new GetInterventionStatusRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetInterventionStatusRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Control.InterventionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInterventionStatusRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInterventionStatusRequest(GetInterventionStatusRequest other) : this() {
      interventionId_ = other.interventionId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInterventionStatusRequest Clone() {
      return new GetInterventionStatusRequest(this);
    }

    /// <summary>Field number for the "intervention_id" field.</summary>
    public const int InterventionIdFieldNumber = 1;
    private string interventionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InterventionId {
      get { return interventionId_; }
      set {
        interventionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetInterventionStatusRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetInterventionStatusRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InterventionId != other.InterventionId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (InterventionId.Length != 0) hash ^= InterventionId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InterventionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InterventionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InterventionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InterventionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (InterventionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InterventionId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetInterventionStatusRequest other) {
      if (other == null) {
        return;
      }
      if (other.InterventionId.Length != 0) {
        InterventionId = other.InterventionId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            InterventionId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            InterventionId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetInterventionStatusResponse : pb::IMessage<GetInterventionStatusResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetInterventionStatusResponse> _parser = new pb::MessageParser<GetInterventionStatusResponse>(() => new GetInterventionStatusResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetInterventionStatusResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Control.InterventionReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInterventionStatusResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInterventionStatusResponse(GetInterventionStatusResponse other) : this() {
      interventionId_ = other.interventionId_;
      kind_ = other.kind_;
      active_ = other.active_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInterventionStatusResponse Clone() {
      return new GetInterventionStatusResponse(this);
    }

    /// <summary>Field number for the "intervention_id" field.</summary>
    public const int InterventionIdFieldNumber = 1;
    private string interventionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InterventionId {
      get { return interventionId_; }
      set {
        interventionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 2;
    private global::Routeiq.V1.Control.InterventionKind kind_ = global::Routeiq.V1.Control.InterventionKind.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Routeiq.V1.Control.InterventionKind Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "active" field.</summary>
    public const int ActiveFieldNumber = 3;
    private bool active_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Active {
      get { return active_; }
      set {
        active_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetInterventionStatusResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetInterventionStatusResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InterventionId != other.InterventionId) return false;
      if (Kind != other.Kind) return false;
      if (Active != other.Active) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (InterventionId.Length != 0) hash ^= InterventionId.GetHashCode();
      if (Kind != global::Routeiq.V1.Control.InterventionKind.Unspecified) hash ^= Kind.GetHashCode();
      if (Active != false) hash ^= Active.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InterventionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InterventionId);
      }
      if (Kind != global::Routeiq.V1.Control.InterventionKind.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      if (Active != false) {
        output.WriteRawTag(24);
        output.WriteBool(Active);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InterventionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InterventionId);
      }
      if (Kind != global::Routeiq.V1.Control.InterventionKind.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      if (Active != false) {
        output.WriteRawTag(24);
        output.WriteBool(Active);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (InterventionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InterventionId);
      }
      if (Kind != global::Routeiq.V1.Control.InterventionKind.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (Active != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetInterventionStatusResponse other) {
      if (other == null) {
        return;
      }
      if (other.InterventionId.Length != 0) {
        InterventionId = other.InterventionId;
      }
      if (other.Kind != global::Routeiq.V1.Control.InterventionKind.Unspecified) {
        Kind = other.Kind;
      }
      if (other.Active != false) {
        Active = other.Active;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            InterventionId = input.ReadString();
            break;
          }
          case 16: {
            Kind = (global::Routeiq.V1.Control.InterventionKind) input.ReadEnum();
            break;
          }
          case 24: {
            Active = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            InterventionId = input.ReadString();
            break;
          }
          case 16: {
            Kind = (global::Routeiq.V1.Control.InterventionKind) input.ReadEnum();
            break;
          }
          case 24: {
            Active = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
