// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: routeiq/v1/admin/slo_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Routeiq.V1.Admin {

  /// <summary>Holder for reflection information generated from routeiq/v1/admin/slo_config.proto</summary>
  public static partial class SloConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for routeiq/v1/admin/slo_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SloConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFyb3V0ZWlxL3YxL2FkbWluL3Nsb19jb25maWcucHJvdG8SEHJvdXRlaXEu",
            "djEuYWRtaW4ijgEKC1Nsb092ZXJyaWRlEhsKCW1ldHJpY19pZBgBIAEoCVII",
            "bWV0cmljSWQSIQoMd29ya3NwYWNlX2lkGAIgASgJUgt3b3Jrc3BhY2VJZBIS",
            "CgR0aWVyGAMgASgJUgR0aWVyEisKEXRhcmdldF9leHByZXNzaW9uGAQgASgJ",
            "UhB0YXJnZXRFeHByZXNzaW9uIm4KDFNsb092ZXJyaWRlcxIhCgx3b3Jrc3Bh",
            "Y2VfaWQYASABKAlSC3dvcmtzcGFjZUlkEjsKCW92ZXJyaWRlcxgCIAMoCzId",
            "LnJvdXRlaXEudjEuYWRtaW4uU2xvT3ZlcnJpZGVSCW92ZXJyaWRlcyI7ChZH",
            "ZXRTbG9PdmVycmlkZXNSZXF1ZXN0EiEKDHdvcmtzcGFjZV9pZBgBIAEoCVIL",
            "d29ya3NwYWNlSWQiUgoVU2V0U2xvT3ZlcnJpZGVSZXF1ZXN0EjkKCG92ZXJy",
            "aWRlGAEgASgLMh0ucm91dGVpcS52MS5hZG1pbi5TbG9PdmVycmlkZVIIb3Zl",
            "cnJpZGUibgoYRGVsZXRlU2xvT3ZlcnJpZGVSZXF1ZXN0EhsKCW1ldHJpY19p",
            "ZBgBIAEoCVIIbWV0cmljSWQSIQoMd29ya3NwYWNlX2lkGAIgASgJUgt3b3Jr",
            "c3BhY2VJZBISCgR0aWVyGAMgASgJUgR0aWVyMqoCChBTbG9Db25maWdTZXJ2",
            "aWNlElsKD0dldFNsb092ZXJyaWRlcxIoLnJvdXRlaXEudjEuYWRtaW4uR2V0",
            "U2xvT3ZlcnJpZGVzUmVxdWVzdBoeLnJvdXRlaXEudjEuYWRtaW4uU2xvT3Zl",
            "cnJpZGVzElgKDlNldFNsb092ZXJyaWRlEicucm91dGVpcS52MS5hZG1pbi5T",
            "ZXRTbG9PdmVycmlkZVJlcXVlc3QaHS5yb3V0ZWlxLnYxLmFkbWluLlNsb092",
            "ZXJyaWRlEl8KEURlbGV0ZVNsb092ZXJyaWRlEioucm91dGVpcS52MS5hZG1p",
            "bi5EZWxldGVTbG9PdmVycmlkZVJlcXVlc3QaHi5yb3V0ZWlxLnYxLmFkbWlu",
            "LlNsb092ZXJyaWRlc0KOAQouYnVpbGQuYnVmLmdlbi5zc2ZvcmdlLnJvdXRl",
            "aXEucm91dGVpcS52MS5hZG1pbkIOU2xvQ29uZmlnUHJvdG9aTGJ1Zi5idWls",
            "ZC9nZW4vZ28vc3Nmb3JnZS9yb3V0ZWlxL3Byb3RvY29sYnVmZmVycy9nby9y",
            "b3V0ZWlxL3YxL2FkbWluO2FkbWludjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Admin.SloOverride), global::Routeiq.V1.Admin.SloOverride.Parser, new[]{ "MetricId", "WorkspaceId", "Tier", "TargetExpression" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Admin.SloOverrides), global::Routeiq.V1.Admin.SloOverrides.Parser, new[]{ "WorkspaceId", "Overrides" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Admin.GetSloOverridesRequest), global::Routeiq.V1.Admin.GetSloOverridesRequest.Parser, new[]{ "WorkspaceId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Admin.SetSloOverrideRequest), global::Routeiq.V1.Admin.SetSloOverrideRequest.Parser, new[]{ "Override" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Routeiq.V1.Admin.DeleteSloOverrideRequest), global::Routeiq.V1.Admin.DeleteSloOverrideRequest.Parser, new[]{ "MetricId", "WorkspaceId", "Tier" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SloOverride : pb::IMessage<SloOverride>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SloOverride> _parser = new pb::MessageParser<SloOverride>(() => new SloOverride());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SloOverride> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Admin.SloConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SloOverride() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SloOverride(SloOverride other) : this() {
      metricId_ = other.metricId_;
      workspaceId_ = other.workspaceId_;
      tier_ = other.tier_;
      targetExpression_ = other.targetExpression_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SloOverride Clone() {
      return new SloOverride(this);
    }

    /// <summary>Field number for the "metric_id" field.</summary>
    public const int MetricIdFieldNumber = 1;
    private string metricId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MetricId {
      get { return metricId_; }
      set {
        metricId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "workspace_id" field.</summary>
    public const int WorkspaceIdFieldNumber = 2;
    private string workspaceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WorkspaceId {
      get { return workspaceId_; }
      set {
        workspaceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tier" field.</summary>
    public const int TierFieldNumber = 3;
    private string tier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Tier {
      get { return tier_; }
      set {
        tier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "target_expression" field.</summary>
    public const int TargetExpressionFieldNumber = 4;
    private string targetExpression_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetExpression {
      get { return targetExpression_; }
      set {
        targetExpression_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SloOverride);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SloOverride other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MetricId != other.MetricId) return false;
      if (WorkspaceId != other.WorkspaceId) return false;
      if (Tier != other.Tier) return false;
      if (TargetExpression != other.TargetExpression) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MetricId.Length != 0) hash ^= MetricId.GetHashCode();
      if (WorkspaceId.Length != 0) hash ^= WorkspaceId.GetHashCode();
      if (Tier.Length != 0) hash ^= Tier.GetHashCode();
      if (TargetExpression.Length != 0) hash ^= TargetExpression.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MetricId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MetricId);
      }
      if (WorkspaceId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(WorkspaceId);
      }
      if (Tier.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tier);
      }
      if (TargetExpression.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TargetExpression);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MetricId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MetricId);
      }
      if (WorkspaceId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(WorkspaceId);
      }
      if (Tier.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tier);
      }
      if (TargetExpression.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TargetExpression);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MetricId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MetricId);
      }
      if (WorkspaceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WorkspaceId);
      }
      if (Tier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tier);
      }
      if (TargetExpression.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetExpression);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SloOverride other) {
      if (other == null) {
        return;
      }
      if (other.MetricId.Length != 0) {
        MetricId = other.MetricId;
      }
      if (other.WorkspaceId.Length != 0) {
        WorkspaceId = other.WorkspaceId;
      }
      if (other.Tier.Length != 0) {
        Tier = other.Tier;
      }
      if (other.TargetExpression.Length != 0) {
        TargetExpression = other.TargetExpression;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MetricId = input.ReadString();
            break;
          }
          case 18: {
            WorkspaceId = input.ReadString();
            break;
          }
          case 26: {
            Tier = input.ReadString();
            break;
          }
          case 34: {
            TargetExpression = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MetricId = input.ReadString();
            break;
          }
          case 18: {
            WorkspaceId = input.ReadString();
            break;
          }
          case 26: {
            Tier = input.ReadString();
            break;
          }
          case 34: {
            TargetExpression = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SloOverrides : pb::IMessage<SloOverrides>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SloOverrides> _parser = new pb::MessageParser<SloOverrides>(() => new SloOverrides());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SloOverrides> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Admin.SloConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SloOverrides() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SloOverrides(SloOverrides other) : this() {
      workspaceId_ = other.workspaceId_;
      overrides_ = other.overrides_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SloOverrides Clone() {
      return new SloOverrides(this);
    }

    /// <summary>Field number for the "workspace_id" field.</summary>
    public const int WorkspaceIdFieldNumber = 1;
    private string workspaceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WorkspaceId {
      get { return workspaceId_; }
      set {
        workspaceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "overrides" field.</summary>
    public const int OverridesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Routeiq.V1.Admin.SloOverride> _repeated_overrides_codec
        = pb::FieldCodec.ForMessage(18, global::Routeiq.V1.Admin.SloOverride.Parser);
    private readonly pbc::RepeatedField<global::Routeiq.V1.Admin.SloOverride> overrides_ = new pbc::RepeatedField<global::Routeiq.V1.Admin.SloOverride>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Routeiq.V1.Admin.SloOverride> Overrides {
      get { return overrides_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SloOverrides);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SloOverrides other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WorkspaceId != other.WorkspaceId) return false;
      if(!overrides_.Equals(other.overrides_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WorkspaceId.Length != 0) hash ^= WorkspaceId.GetHashCode();
      hash ^= overrides_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WorkspaceId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WorkspaceId);
      }
      overrides_.WriteTo(output, _repeated_overrides_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WorkspaceId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WorkspaceId);
      }
      overrides_.WriteTo(ref output, _repeated_overrides_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WorkspaceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WorkspaceId);
      }
      size += overrides_.CalculateSize(_repeated_overrides_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SloOverrides other) {
      if (other == null) {
        return;
      }
      if (other.WorkspaceId.Length != 0) {
        WorkspaceId = other.WorkspaceId;
      }
      overrides_.Add(other.overrides_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            WorkspaceId = input.ReadString();
            break;
          }
          case 18: {
            overrides_.AddEntriesFrom(input, _repeated_overrides_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            WorkspaceId = input.ReadString();
            break;
          }
          case 18: {
            overrides_.AddEntriesFrom(ref input, _repeated_overrides_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetSloOverridesRequest : pb::IMessage<GetSloOverridesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetSloOverridesRequest> _parser = new pb::MessageParser<GetSloOverridesRequest>(() => new GetSloOverridesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetSloOverridesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Admin.SloConfigReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSloOverridesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSloOverridesRequest(GetSloOverridesRequest other) : this() {
      workspaceId_ = other.workspaceId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSloOverridesRequest Clone() {
      return new GetSloOverridesRequest(this);
    }

    /// <summary>Field number for the "workspace_id" field.</summary>
    public const int WorkspaceIdFieldNumber = 1;
    private string workspaceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WorkspaceId {
      get { return workspaceId_; }
      set {
        workspaceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetSloOverridesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetSloOverridesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WorkspaceId != other.WorkspaceId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WorkspaceId.Length != 0) hash ^= WorkspaceId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WorkspaceId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WorkspaceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WorkspaceId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WorkspaceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WorkspaceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WorkspaceId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetSloOverridesRequest other) {
      if (other == null) {
        return;
      }
      if (other.WorkspaceId.Length != 0) {
        WorkspaceId = other.WorkspaceId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            WorkspaceId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            WorkspaceId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SetSloOverrideRequest : pb::IMessage<SetSloOverrideRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SetSloOverrideRequest> _parser = new pb::MessageParser<SetSloOverrideRequest>(() => new SetSloOverrideRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SetSloOverrideRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Admin.SloConfigReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetSloOverrideRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetSloOverrideRequest(SetSloOverrideRequest other) : this() {
      override_ = other.override_ != null ? other.override_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetSloOverrideRequest Clone() {
      return new SetSloOverrideRequest(this);
    }

    /// <summary>Field number for the "override" field.</summary>
    public const int OverrideFieldNumber = 1;
    private global::Routeiq.V1.Admin.SloOverride override_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Routeiq.V1.Admin.SloOverride Override {
      get { return override_; }
      set {
        override_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SetSloOverrideRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SetSloOverrideRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Override, other.Override)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (override_ != null) hash ^= Override.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (override_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Override);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (override_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Override);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (override_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Override);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SetSloOverrideRequest other) {
      if (other == null) {
        return;
      }
      if (other.override_ != null) {
        if (override_ == null) {
          Override = new global::Routeiq.V1.Admin.SloOverride();
        }
        Override.MergeFrom(other.Override);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (override_ == null) {
              Override = new global::Routeiq.V1.Admin.SloOverride();
            }
            input.ReadMessage(Override);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (override_ == null) {
              Override = new global::Routeiq.V1.Admin.SloOverride();
            }
            input.ReadMessage(Override);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DeleteSloOverrideRequest : pb::IMessage<DeleteSloOverrideRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeleteSloOverrideRequest> _parser = new pb::MessageParser<DeleteSloOverrideRequest>(() => new DeleteSloOverrideRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeleteSloOverrideRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Routeiq.V1.Admin.SloConfigReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteSloOverrideRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteSloOverrideRequest(DeleteSloOverrideRequest other) : this() {
      metricId_ = other.metricId_;
      workspaceId_ = other.workspaceId_;
      tier_ = other.tier_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteSloOverrideRequest Clone() {
      return new DeleteSloOverrideRequest(this);
    }

    /// <summary>Field number for the "metric_id" field.</summary>
    public const int MetricIdFieldNumber = 1;
    private string metricId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MetricId {
      get { return metricId_; }
      set {
        metricId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "workspace_id" field.</summary>
    public const int WorkspaceIdFieldNumber = 2;
    private string workspaceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WorkspaceId {
      get { return workspaceId_; }
      set {
        workspaceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tier" field.</summary>
    public const int TierFieldNumber = 3;
    private string tier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Tier {
      get { return tier_; }
      set {
        tier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeleteSloOverrideRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeleteSloOverrideRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MetricId != other.MetricId) return false;
      if (WorkspaceId != other.WorkspaceId) return false;
      if (Tier != other.Tier) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MetricId.Length != 0) hash ^= MetricId.GetHashCode();
      if (WorkspaceId.Length != 0) hash ^= WorkspaceId.GetHashCode();
      if (Tier.Length != 0) hash ^= Tier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MetricId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MetricId);
      }
      if (WorkspaceId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(WorkspaceId);
      }
      if (Tier.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MetricId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MetricId);
      }
      if (WorkspaceId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(WorkspaceId);
      }
      if (Tier.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MetricId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MetricId);
      }
      if (WorkspaceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WorkspaceId);
      }
      if (Tier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeleteSloOverrideRequest other) {
      if (other == null) {
        return;
      }
      if (other.MetricId.Length != 0) {
        MetricId = other.MetricId;
      }
      if (other.WorkspaceId.Length != 0) {
        WorkspaceId = other.WorkspaceId;
      }
      if (other.Tier.Length != 0) {
        Tier = other.Tier;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MetricId = input.ReadString();
            break;
          }
          case 18: {
            WorkspaceId = input.ReadString();
            break;
          }
          case 26: {
            Tier = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MetricId = input.ReadString();
            break;
          }
          case 18: {
            WorkspaceId = input.ReadString();
            break;
          }
          case 26: {
            Tier = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
